<div class="row-fluid">
  <div class="span6">
    <form method="post" enctype="multipart/form-data">
      <label class="btn" for="fileUpload">Upload</label>
      <input type="file" name="file" id="fileUpload">
    </form>
  </div>
  <div class="span6">
    <form>
      <div>
        <input type="text" id="codeBox" name="code">
      </div>
      <div>
        <input class="btn" type="submit" value="Download">
      </div>
    </form>
  </div>
</div>
