<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Small File Storage</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="<?php echo _static_url('css/bootstrap.min.css') ?>" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      #fileUpload {
        visibility: hidden;
      }
    </style>

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <h3 class="muted">
          <a href="/">Small File Storage</a>
        </h3>
      </div>

      <hr>

      <div><?php $this->yield() ?></div>

      <hr>

      <div class="footer">
        <p>By <a href="https://github.com/picasso250">Xiaochi</a></p>
      </div>

    </div> <!-- /container -->

    <script type="text/javascript" src="<?php echo _static_url('js/jquery-1.9.1.min.js') ?>"></script>
    <script type="text/javascript">
    $(function () {
      $('#fileUpload').change(function () {
        var label = $('label[for=fileUpload]').text('uploading...');
        $(this).parent('form').submit();
        label.prop('disabled', true);
      });
    });
    </script>

  </body>
</html>

